### ISSUE TITLE
index out of range when using "value_a0 = tf.gather(input_feature_flat, index_a0)"

### ISSUE THREAD

**Issue by WMeixiang** [XiangLi-Shaun/deformableConvolution#1]
![image](https://user-images.githubusercontent.com/47051563/69946262-480d6780-1526-11ea-8edd-61f7dd391490.png)
I test it by a simple code below: 
![image](https://user-images.githubusercontent.com/47051563/69946421-886ce580-1526-11ea-9eeb-d561af9680f3.png)

so How to fix this problem?? Thank you!

**Comment by WMeixiang** [comment]
# get 8 grid values  ([N*H*W*D,C], [N*H*W*D*27])
            value_a0 = tf.gather(input_feature_flat, index_a0) .  #cause error:  out of range
            value_b0 = tf.gather(input_feature_flat, index_b0)
my test code:>>> import tensorflow as tf
>>> N = 2
>>> H = 3
>>> W = 3
>>> D = 2
>>> C = 5
>>> input = tf.reshape(tf.range(0,180),(N*H*W*D, C))
>>> print(input.shape)
(36, 5)
>>> kernel = 3
>>> index = tf.reshape(tf.range(0,540),[-1])
>>> print(index.shape)
(540,)
>>> value = tf.gather(input,index)
>>> with tf.Session() as sess:
...     print(sess.run(value))
... 
2019-12-02 16:58:53.846784: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-12-02 16:58:53.849933: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/Users/pc/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/pc/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/pc/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[36] = 36 is not in [0, 36)
